services:
  db:
    image: postgres:15
    container_name: postgres_piscine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../ex02:/scripts
      - ../data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_piscine
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "8080:80"
    restart: always

volumes:
  postgres_data:
